### ISSUE TITLE
Add Basic Form Authentication

### ISSUE THREAD

**Issue by BMNTeam** [NeuraLegion/brokencrystals#30]
Simple HTTP form with standard Authorization header flow

**Comment by BMNTeam** [comment]
@pmstss, @derevnjuk, @ArtLinkov, @Artur-UX-Designer Suggested UI changes, please check them out when you get a chance.

<details>
<img width="1680" alt="Screenshot 2021-04-15 at 16 03 57" src="https://user-images.githubusercontent.com/13920216/114873850-65ce2a80-9e04-11eb-92b1-7b74bf268902.png">
<summary>Select</summary>
</details>

<details>
<img width="1676" alt="Screenshot 2021-04-15 at 16 04 06" src="https://user-images.githubusercontent.com/13920216/114873889-6ff02900-9e04-11eb-984a-38ee899e3d77.png">
<summary>Select opened</summary>
</details>

**Comment by ArtLinkov** [comment]
@BMNTeam let's make it a bit more generic, since we are going to add more types soon :)

How about the following suggestions:
* Change `Request Type` to `Authentication Type`, and place it at the top (so that when there will be more fields it will stay in the same place)
* Rename `Application JSON` to `Simple REST-based Authentication`
* Rename `HTML form` to `Simple HTML Form-based Authentication`
