### ISSUE TITLE
Add simple GET-based CSRF Multi-Step Auth flow to BC

### ISSUE THREAD

**Issue by derevnjuk** [NeuraLegion/brokencrystals#32]
A simple multi-step flow where the user must do:

1. `GET` to the login page (i.e `GET /auth/simple-csrf-flow`) to get a csrf token from the response
2. `POST` to the auth API endpoint with that token and valid credentials

**Comment by BMNTeam** [comment]
@ArtLinkov, could you please, share your thoughts, would it be on the same login page as Html based option, just as another option, or it's better to have another (route/UI) for this feature?

**Comment by ArtLinkov** [comment]
@BMNTeam it would best to have all the logins on the same URL, with changing form parameters.
If we have multiple different paths for the various logins. it could be more difficult to configure a scan because then you will need to exclude a list of URLs every time (except the one authentication that you would want to use)

**Comment by BMNTeam** [comment]
@alexandrmiee, I've mocked request as:
`/api/auth/simple-csrf-flow` `GET`
Suggested model:
<pre>
export enum AuthType {
  FORM_BASED = 'application/x-www-form-urlencoded',
  APPLICATION_JSON = 'application/json'
}

export interface LoginUser {
  user: string;
  password: string;
  op?: AuthType;
  csrf?: string;
}
</pre>

Additional model, use to determine what type of authentication should be shown in UI, maybe we can draw on it between communication Headers/Body, please share your thought.
<pre>
enum FormMode {
  BASIC = 'basic',
  HTML = 'html',
  CSRF = 'csrf'
}
</pre>
